title: "Jonathan Sebastian Moiras"
description: >
  Data Science Student @ Binus University  
description: "Data Science Portfolio"
theme: jekyll-theme-minimal
logo: /assets/Profile.jpg  
show_downloads: false
