title: "Jonathan Sebastian Moiras"
description: >
  Hi, I'm Jonathan Sebastian — a Data Science undergraduate at BINUS University.  
  I specialize in machine learning, NLP, and data visualization.
theme: jekyll-theme-minimal
logo: /assets/Profile.jpg  
show_downloads: false
